# Generated by Django 4.0.4 on 2022-05-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='sf', max_length=2),
            preserve_default=False,
        ),
    ]
