# Generated by Django 4.0.4 on 2022-06-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_users_email_alter_users_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trading_Pairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.CharField(max_length=100)),
                ('sell', models.CharField(max_length=100)),
            ],
        ),
    ]
